- name: Install NGINX
  yum:
    name: nginx
    state: present

- name: Enable and start NGINX
  service:
    name: nginx
    state: started
    enabled: yes

- name: Configure NGINX load balancer
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload nginx

