---
- name: Install NFS packages
  ansible.builtin.yum:
    name: nfs-utils
    state: present

- name: Enable and start NFS services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - nfs-server
    - rpcbind

- name: Create export directory
  ansible.builtin.file:
    path: /home/bitrix/www
    state: directory
    mode: '0755'

- name: Configure /etc/exports
  ansible.builtin.copy:
    dest: /etc/exports
    content: |
      /home/bitrix/www 192.168.1.108(rw,sync,no_root_squash) 192.168.1.20(rw,sync,no_root_squash)

- name: Reload NFS exports
  ansible.builtin.command: exportfs -ra

# tasks file for roles/nfs_server
